# Copyright (c) Aemon Cannon. All rights reserved.
# The use and distribution terms for this software are covered by the
# Common Public License 1.0 (http://opensource.org/licenses/cpl.php)
# which can be found in the file CPL.TXT at the root of this distribution.
# By using this software in any fashion, you are agreeing to be bound by
# the terms of this license.
# You must not remove this notice, or any other, from this software.


$debug = true

MXMLC = PLATFORM =~ /win/ ? "mxmlc.exe -target-player=10.0.0" : "mxmlc -target-player=10.0.0"
COMPC = PLATFORM =~ /win/ ? "compc.exe -target-player=10.0.0" : "compc -target-player=10.0.0"
DEBUG_PROJECTOR = PLATFORM =~ /win/ ? "sa_flashplayer_10_debug.exe" : "~/bin/flashplayer_debug_projector_10"

SHARED_CLASS_PATH = [
                     "src",
                     File.expand_path("~/lib/flexunit/trunk/FlexUnitLib/src")
                    ]

COMPILE_OPTIONS = [
                   "+configname=flex",
                   "-default-frame-rate=60",
                   "-compiler.warn-no-type-decl=false",
                   "-compiler.optimize=true",
                   "-compiler.source-path #{SHARED_CLASS_PATH.join(" ")}",
                   "-use-network=true"
                  ]

SHARED_SOURCES = FileList["./src/**/*"]

ROUTER_CON_HARNESS = "./bin/router_con_harness.swf"
file ROUTER_CON_HARNESS => SHARED_SOURCES do
  options = COMPILE_OPTIONS + [$debug ? "-compiler.debug=true" : "", "-default-size 500 500"]
  sh "#{MXMLC} #{options.join(" ")} -file-specs src/com/croqodile/test/RouterConnectionHarness.as -output=#{ROUTER_CON_HARNESS}"
end

UNIT_TEST_RUNNER_TARGET = "./bin/unit_test_runner.swf"
file UNIT_TEST_RUNNER_TARGET => SHARED_SOURCES do
  options = COMPILE_OPTIONS + [$debug ? "-compiler.debug=true" : "", "-default-size 1000 600"]
  sh "#{MXMLC} #{options.join(" ")} -file-specs src/com/croqodile/test/FlexUnitTestRunner.mxml -output=#{UNIT_TEST_RUNNER_TARGET}"
end

DEMO_TANKWARS_TARGET = "./bin/tankwars.swf"
file DEMO_TANKWARS_TARGET => SHARED_SOURCES do
  options = COMPILE_OPTIONS + [$debug ? "-compiler.debug=true" : "", "-default-size 1000 600"]
  sh "#{MXMLC} #{options.join(" ")} -compiler.incremental=true -file-specs src/com/croqodile/demos/tankwars/Main.as -output=#{DEMO_TANKWARS_TARGET}"
end

task :units => [UNIT_TEST_RUNNER_TARGET] do
  sh "#{DEBUG_PROJECTOR} #{UNIT_TEST_RUNNER_TARGET}"
end

task :tankwars => [DEMO_TANKWARS_TARGET] do
end

task :router_con_harness => [ROUTER_CON_HARNESS] do
  sh "#{DEBUG_PROJECTOR} #{ROUTER_CON_HARNESS}"
end
