#! ruby
require 'fileutils'
require 'webrick'
require 'date'
require 'net/http'


rule '.beam' => '.erl' do |t|
   sh "erlc #{t.source}"
end

ALL_BEAMS = FileList["*.erl"].gsub(".erl", ".beam")

task :build => ALL_BEAMS

task :im => [:build] do
  sh "erl -sname im_node -eval \"application:start(island_manager).\""
end

task :init_db => [:build] do
  sh "erl -sname im_node -eval \"island_data:start_and_create_schema().\""
end

task :test => [:build] do
  sh "erl -sname im_test_node -eval \"island_test:run(),init:stop().\""
end

task :repl => [:build] do
  sh "erl"
end

task :clean => [] do
  rm FileList["*.beam"]
end

task :default => [:compile_and_launch]
